---
- hosts: ci-servers
  user: root
  vars_files:
    - vars.yaml

  tasks:
    - name: install system packages
      apt: pkg=${item} state=installed
      with_items: ${system_packages}

    - name: enable jenkins
      service: name=jenkins state=started

    - name: create project dir
      file: state=directory owner=${username} path=${project_root} recurse=yes